name: sql_outh_try_external
description: ''
version: '1'
author: sony@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/oauth_job:
    name: oauth_job
    description: ''
    fabricUID: 2522
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: prophecy_internal_jobs
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-05-29 13:06:10'
    author: sony@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-05-29 13:04:24'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/testmodel:
    name: testmodel
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: c_short
        dataType:
          type: SmallInt
      - name: c_int
        dataType:
          type: Integer
      - name: c_long
        dataType:
          type: Bigint
      - name: c_decimal
        dataType:
          type: Decimal
      - name: c_float
        dataType:
          type: Float
      - name: c_boolean
        dataType:
          type: Boolean
      - name: c_double
        dataType:
          type: Double
      - name: c_string
        dataType:
          type: String
      - name: c_date
        dataType:
          type: Date
      - name: c_timestamp
        dataType:
          type: Timestamp
      - name: c_array_int
        dataType:
          type: Array
          dataType:
            type: Integer
      - name: c_array_string
        dataType:
          type: Array
          dataType:
            type: String
      - name: c_array_long
        dataType:
          type: Array
          dataType:
            type: Bigint
      - name: c_array_boolean
        dataType:
          type: Array
          dataType:
            type: Boolean
      - name: c_array_date
        dataType:
          type: Array
          dataType:
            type: Date
      - name: c_array_timestamp
        dataType:
          type: Array
          dataType:
            type: Timestamp
      - name: c_array_float
        dataType:
          type: Array
          dataType:
            type: Float
      - name: c_array_decimal
        dataType:
          type: Array
          dataType:
            type: Decimal
      - name: c_struct
        dataType:
          type: Struct
          fields:
          - name: c_short
            dataType:
              type: SmallInt
          - name: c_int
            dataType:
              type: Integer
          - name: c_long
            dataType:
              type: Bigint
          - name: c_decimal
            dataType:
              type: Decimal
          - name: c_float
            dataType:
              type: Float
          - name: c_boolean
            dataType:
              type: Boolean
          - name: c_double
            dataType:
              type: Double
          - name: c_string
            dataType:
              type: String
          - name: c_date
            dataType:
              type: Date
          - name: c_timestamp
            dataType:
              type: Timestamp
          - name: c_array_int
            dataType:
              type: Array
              dataType:
                type: Integer
    description: null
    author: sony@prophecy.io
    files:
    - models/testmodel.sql
    - .prophecy/ide/models/testmodel.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-05-29 13:05:02'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: sony@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-05-29 13:04:28'
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/hive_metastore_sony:
    name: hive_metastore.sony
    description: null
    author: sony@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2025-05-29 13:05:16'
    tables:
    - name: test112
      schema:
        entityType: ''
        providerType: databricks
        fields:
        - name: c_short
          dataType:
            type: SmallInt
        - name: c_int
          dataType:
            type: Integer
        - name: c_long
          dataType:
            type: Bigint
        - name: c_decimal
          dataType:
            type: Decimal
        - name: c_float
          dataType:
            type: Float
        - name: c_boolean
          dataType:
            type: Boolean
        - name: c_double
          dataType:
            type: Double
        - name: c_string
          dataType:
            type: String
        - name: c_date
          dataType:
            type: Date
        - name: c_timestamp
          dataType:
            type: Timestamp
        - name: c_array_int
          dataType:
            type: Array
            dataType:
              type: Integer
        - name: c_array_string
          dataType:
            type: Array
            dataType:
              type: String
        - name: c_array_long
          dataType:
            type: Array
            dataType:
              type: Bigint
        - name: c_array_boolean
          dataType:
            type: Array
            dataType:
              type: Boolean
        - name: c_array_date
          dataType:
            type: Array
            dataType:
              type: Date
        - name: c_array_timestamp
          dataType:
            type: Array
            dataType:
              type: Timestamp
        - name: c_array_float
          dataType:
            type: Array
            dataType:
              type: Float
        - name: c_array_decimal
          dataType:
            type: Array
            dataType:
              type: Decimal
        - name: c_struct
          dataType:
            type: Struct
            fields:
            - name: c_short
              dataType:
                type: SmallInt
              description: A small integer value within the structured data
            - name: c_int
              dataType:
                type: Integer
              description: An integer value within the structured data
            - name: c_long
              dataType:
                type: Bigint
              description: Long integer value within the structured data
            - name: c_decimal
              dataType:
                type: Decimal
              description: Decimal value within the structured data
            - name: c_float
              dataType:
                type: Float
              description: Floating-point value within the structured data
            - name: c_boolean
              dataType:
                type: Boolean
              description: Boolean value indicating a specific condition within the
                structured data
            - name: c_double
              dataType:
                type: Double
              description: Double precision value representing a measurement within
                the structured data
            - name: c_string
              dataType:
                type: String
              description: String value containing textual information within the
                structured data
            - name: c_date
              dataType:
                type: Date
              description: Date value within the structured data
            - name: c_timestamp
              dataType:
                type: Timestamp
              description: Timestamp value within the structured data
            - name: c_array_int
              dataType:
                type: Array
                dataType:
                  type: Integer
              description: Array of integer values within the structured data
      description: Diverse test dataset containing various data types for comprehensive
        analysis and validation purposes.
      author: sony@prophecy.io
      createdAt: '2025-05-29 13:05:16'
      tableType: table
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2025-05-29 13:04:24'
dependencies: []
projectDependencies:
  '22363':
    projectUID: 22363
    projectName: ProphecyDatabricksSqlBasics
    repositoryPath: gitUri=https://github.com/prophecy-io/databricks-sql-basics&subPath=
    version: 0.0.7.dev0
    isDefault: true
    author: null
    createdAt: '2025-05-29 13:04:12'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
